export type FigureSeries = string

export interface FigureItem {
	series: FigureSeries
	name: string
	owned: boolean
	isHidden: boolean
	image: string
	scale?: number
}

const figures: FigureItem[] = [
	{
		series: '悠悠日常',
		name: '啊啊啊爱你',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195918.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '略略略出来玩',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195914.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '抠抠脚发发呆',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195912.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '突然就难过了',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195948.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '我怎么这么好看',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195946.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '颤抖吧！我的脂肪',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195944.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '嘻嘻嘻零食自由',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195934.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '呜呜呜看哭了',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195928.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '沉浸式追剧',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195906.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '洗香香',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195926.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '什么瓜？',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195920.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '是锅先动的手',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195849.jpg',
		scale: 1,
	},
	{
		series: '悠悠日常',
		name: '我要认真减肥了',
		owned: false,
		isHidden: true,
		image: 'https://cdn.atao.cyou/Web/web_250830_195910.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '小本生意，假一赔十',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195851.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '猪师傅，我赶时间',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195843.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '换个发型换个心情',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195908.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '感觉身体被掏空',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195916.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '珍珠奶茶真好喝',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195857.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '嘬嘬嘬嘬',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195845.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '早八真的困',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195841.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '微笑小刘为您服务',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195901.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '带薪拉屎有点麻',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195924.jpg',
		scale: 1,
	},
	{
		series: '不正经博物馆',
		name: '打工是不可能打工的',
		owned: false,
		isHidden: true,
		image: 'https://cdn.atao.cyou/Web/web_250830_195847.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '选A还是选C',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195950.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '零钱罐摔碎了',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195853.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '下雨天快乐',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195855.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '我可真时髦',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195936.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '下次不敢啦！',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195940.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '又被骗了',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195938.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '我倒要看看',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195932.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '看我的奖状！',
		owned: false,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_204434.png',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '头皮紧紧的！',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195904.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '你看我能这样',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195930.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '给小流浪送饭',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195922.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '才艺表演我最行',
		owned: true,
		isHidden: false,
		image: 'https://cdn.atao.cyou/Web/web_250830_195942.jpg',
		scale: 1,
	},
	{
		series: '长不大真好',
		name: '扭啊扭出发',
		owned: false,
		isHidden: true,
		image: 'https://cdn.atao.cyou/Web/web_250830_195859.jpg',
		scale: 1,
	},
]

export default figures

